# Generated by Django 4.2.5 on 2023-11-12 09:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="dcenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("city", models.TextField(blank=True)),
                ("pincode", models.TextField(blank=True)),
                ("about", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("quantity", models.TextField(blank=True)),
                (
                    "imgg",
                    models.ImageField(default="profile.webp", upload_to="productimg"),
                ),
                ("majority", models.TextField(blank=True)),
                ("username", models.TextField(blank=True)),
                ("weight", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
                ("timee", models.DateTimeField(default=datetime.datetime.now)),
                ("orderid", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="picker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("password", models.TextField(blank=True)),
                ("phone", models.TextField(blank=True)),
                ("emaill", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(default="profile.webp", upload_to="proimg"),
                ),
                ("address", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("username", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("price", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(default="profile.webp", upload_to="productimg"),
                ),
                ("detail", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="userpro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("fullname", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(default="profile.webp", upload_to="userproimg"),
                ),
                ("password", models.TextField(blank=True)),
                ("pincode", models.TextField(blank=True)),
                ("isverified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
