# Generated by Django 4.2.5 on 2023-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpro",
            name="email_token",
            field=models.CharField(default="", max_length=200),
        ),
    ]
