# Generated by Django 4.2.5 on 2023-11-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0005_alter_userpro_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpro",
            name="user",
        ),
    ]
